version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  assignees:
  - scionaltera
  labels:
  - dependencies
  ignore:
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 6.a, < 7"
  - dependency-name: org.mockito:mockito-core
    versions:
    - "> 3.3.0, < 3.4"
  - dependency-name: org.owasp:dependency-check-gradle
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.projectreactor.netty:reactor-netty
    versions:
    - 1.0.3
    - 1.0.4
    - 1.0.5
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.webjars:bootstrap
    versions:
    - 4.6.0
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: info.solidsoft.gradle.pitest:gradle-pitest-plugin
    versions:
    - 1.5.2
